import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import ChatsSidebar from "@/components/chats-sidebar";
import { ChatProvider } from "@/context/ChatContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full`}
      >
        {/* Code i copied from documentation. SidebarProvider needs to wrap
        everything because it needs the context of the whole page */}
        <SidebarProvider>
          <ChatProvider>
            <ChatsSidebar />
            <main className="flex-1 flex flex-col h-full">
              {/* (uncomment to make sidebar toggleable) <SidebarTrigger /> */}
              {/* {children} */}
            </main>
          </ChatProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
